name: "Import checker"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install isort
      run: pip install isort==5.6.4
      
    - name: Run isort
      run: isort . --sp=pyproject.toml -c